language: minimal

services: 
  - docker

script:
  # Assuming the .travis.yml file is in the project directory, and there is a separate sub-directory for each service
  # Use either `docker-compose` or individual `docker build` commands
  # Build
  - docker build -t udagram-api-feed ./udagram-api-feed
  - docker build -t udagram-api-user ./udagram-api-user
  - docker build -t udagram-frontend ./udagram-frontend
  - docker build -t reverseproxy ./udagram-reverseproxy

  # Tagging
  - docker tag udagram-api-feed vinnytorde/udagram-api-feed:latest
  - docker tag udagram-api-user vinnytorde/udagram-api-user:latest
  - docker tag udagram-frontend vinnytorde/udagram-frontend:latest
  - docker tag reverseproxy vinnytorde/reverseproxy:latest

  # Push
  # Assuming DOCKER_PASSWORD and DOCKER_USERNAME are set in the Travis repository settings
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push vinnytorde/udagram-api-feed:latest
  - docker push vinnytorde/udagram-api-user:latest
  - docker push vinnytorde/udagram-frontend:latest
  - docker push vinnytorde/reverseproxy:latest