# deployment

apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    deployment: reverseproxy
  name: reverseproxy-deployment
spec:
  selector:
    matchLabels:
      app: reverseproxy
  replicas: 1
  template:
    metadata:
      labels:
        app: reverseproxy
    spec:
      containers:
      - image: vinnytorde/reverseproxy:v1
        name: reverseproxy
        imagePullPolicy: Always          
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "1024Mi"
            cpu: "500m"       
        ports:
        - containerPort: 8080
      restartPolicy: Always

---
# service

apiVersion: v1
kind: Service
metadata:
  labels:
    service: reverseproxy
  name: reverseproxy-svc
spec:
  ports:
  - name: "8080"
    port: 8080
    targetPort: 8080 
  selector:
    app: reverseproxy