# deployment

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    service: udagram-frontend
  name: udagram-frontend
spec:
  replicas: 1
  template:
    metadata:
      labels:
        service: udagram-frontend
    spec:
      containers:
      - image: vinnytorde/udagram-frontend
        name: udagram-frontend
        imagePullPolicy: Always          
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "1024Mi"
            cpu: "500m"       
        ports:
        - containerPort: 8080
      restartPolicy: Always

---
# service

apiVersion: v1
kind: Service
metadata:
  labels:
    service: udagram-frontend
  name: udagram-frontend-svc
spec:
  ports:
  - name: "8080"
    port: 8080
    targetPort: 8080 
  selector:
    service: udagram-frontend