# deployment

apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    deployment: udagram-api-user
  name: udagram-api-user-deployment
spec:
  selector:
    matchLabels:
      app: udagram-api-user
  replicas: 1
  template:
    metadata:
      labels:
        app: udagram-api-user
    spec:
      containers:
      - image: vinnytorde/udagram-api-user
        name: udagram-api-user
        imagePullPolicy: Always          
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "2048Mi"
            cpu: "500m"       
        ports:
        - containerPort: 8080
      restartPolicy: Always